version: "3.1"
services:
    app:
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile
        container_name: api-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: api-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "3000:80"
        volumes:
            - ./:/var/www
            - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres:latest
        container_name: api-postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=database
        volumes:
            - ./volumes/dbdata:/var/lib/postgresql/data
        ports:
            - "3001:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
